### PR TITLE
added 'newwindow' to fS* and fT* binding (refs issue #191)

### PR DESCRIPTION
**Pull request by GSI**
How is `fs` to be used?

What is considered "selected link"?

### CODE REVIEW

**Comment by mathstuf** [comment]
Text selection is what triggers the fs bindings (searching also should too, but I forget).

**Comment by keis** [comment]
These bindings are a bit inconsistent also it would make more sense to swap `Fs` and `fS` around to match `fl` so that capital F always means new window. WDYT?

**Comment by GSI** [comment]
Agree. Just wanted to keep the topic separate from the handling of the original "newwindow" issue.

Personally I think bringing up key hints with more than one char is too much - at least "click" should be brought up by just one key and "newwindow" by Shift + the same key.

**Comment by mathstuf** [comment]
I like the patterns made by these. Making one a single character means that nothing else can use that character as a prefix, so all the other bindings would need to migrate elsewhere.

**Comment by mathstuf** [comment]
One improvement might be to do what I do which is to redo the `fl` family be `fa` and only use `asdfg` as the follow keys which allows for one-handed link following (for right-hand mouse users).

**Comment by GSI** [comment]
I am basically thinking of newcomers here.

Personally I don't even use a qwerty/z layout, so I have to customize anyway.

Just changed `fs` to `<Return>` - little pain, much gain;

Anyway, I'd say we just get it consistent in any fashion you feel confortable with and close :)

**Comment by keis** [comment]
Merging this as it's a simple bugfix to the current bindings. Lets use #200 for discussing the default config

**Pull request merged**
