### PR TITLE
defined contrast-rich colors for the status bar

### PR DESCRIPTION
**Pull request by GSI**
I'd like to suggest these colors for the default config. Especially the
**Ins** mode is otherwise easily overlooked.

### CODE REVIEW

**Comment by mathstuf** [comment]
Hmm. This looks like less contrast for me for `Cmd` mode (old on top, new on bottom).

uzbl-contrast

**Comment by mathstuf** [comment]
Maybe the whole color scheme should be moved to Solarized or something?

**Comment by keis** [comment]
I like the idea of making input/command mode more easily recognisable but that green does not look like a good background for the text. Maybe a white would be better?

**Comment by GSI** [comment]
Yep, the green (I guess you tried it manually, because it should be on `Ins`) is actually less contrastful. I figured the important thing in `Ins` is being aware that we are in it, more so than being able to read the status info.

That said I'm also not 100 % happy. It mostly did the trick with least amount of changes. Solarized is a good idea though. I'll see to it.

@keis I tried everything from `#888888` upwards (=> white), but anything brighter makes the status bar almost unreadable given the current fg colors.

**Comment by GSI** [comment]
Took some minutes to get used to, but ultimately I find it looks pretty awesome.

The softer colors make the status bar less obstrusive.

By the way, in the config, is there a way to check if we're on an SSL site?
I want to add an according indicator.

**Comment by GSI** [comment]
Also note that I commented out `cursor_style` `hint_style` and hint style - what are they used for?

Which setting is responible for the color when marking text in the status bar (with the mouse)? That looks pretty bad right now.

**Comment by mathstuf** [comment]
Those are used in the keycmd (`cursor_style`) and completion (`hint_style`) plugins.

**Comment by mathstuf** [comment]
The selection is probably handled by GTK, so if we can find what property to set on the label widgets for that, we can expose it.

**Comment by mathstuf** [comment]
The [`GtkLabel` docs](https://developer.gnome.org/gtk3/stable/GtkLabel.html) seem to indicate it is set via a `.selection` CSS subnode.

**Comment by keis** [comment]
this looks really good :+1:

**Comment by mathstuf** [comment]
Yep, I agree. I'm not really all that into Solarized everywhere, but this is an improvement. Getting the selection stuff fixed can be done with:

```css
#Uzbl label selection {
  background-color: #ffffff;
}
```

in `$XDG_CONFIG_HOME/gtk-3.0/gtk.css`.

**Comment by mathstuf** [comment]
Not that white is the right color, but that's easy to change now.

**Comment by GSI** [comment]
Solarized one-liner:

    echo '#Uzbl label selection {\n  background-color: #fdf6e3;\n}' > "${XDG_CONFIG_HOME}/gtk-3.0/gtk.css"

**Comment by mathstuf** [comment]
Cool, confirmed to look good :) . Could we get that added to the docs? Maybe next to the default configuration?

**Comment by GSI** [comment]
Documented in which sense?

**Comment by mathstuf** [comment]
A new `examples/config/README.md` file explaining the GTK3 CSS style file?

**Comment by GSI** [comment]
> explaining the GTK3 CSS style file?

Could you point out where the app specific part (`#Uzbl`, in this case) and `label selection` are documented?

I found [some references to gtk.css](https://developer.gnome.org/search?q=gtk.css), but nothing that goes into those details.

Also, we would need to overwrite CSS `color` too, but putting it there has no effect. (Tried `!important` too.)

**Comment by mathstuf** [comment]
I don't know where the docs are or if they exist at all. The `#Uzbl` bit is from porting my GTK2 CSS (I have other settings). I found `label selection` by using the GTK Inspector to find out where the declaration for the current color came from and copied it's selector.

**Comment by GSI** [comment]
Added what we know so far (setting `background-color` works).

Though even when setting `color` in the inspector, the change didn't reflect in the UI.

**Comment by mathstuf** [comment]
I had to play around with a lot of things to find the right bit that changed what I wanted. CSS and UI widgets don't really have a good one-to-one correspondence, so it probably isn't anything *too* obvious :) .

**Pull request merged**
