### PR TITLE
introduced 'proxy_section' to status bar (refs issue #194)

### PR DESCRIPTION
**Pull request by GSI**
Note that displaying the @proxy_url with this stopped working some months back.
Now only '/' is shown even though the correct proxy is actually used (localhost..).

### CODE REVIEW

**Comment by GSI** [comment]
Screwed this PR up; closing

**Comment by mathstuf** [comment]
How is it screwed up? If it is code changes, just push to the branch again and they'll show up here.

**Comment by keis** [comment]
Was re-opened as #196 but targeting master. I think you can change that if you click edit but this change is merged now anyway

**Comment by mathstuf** [comment]
Ah, OK. Branch whatnots used to be impossible to change. Haven't had to see if they ever fixed that yet.

**Comment by GSI** [comment]
I had force-pushed my branch, in order to correct something and then that unrelated comment by mathstuff from another PR showed up in this one. The avoid confusion I quickly closed it.

Thanks for merging and resolving the soup_url issue!

**Comment by GSI** [comment]
I had force-pushed my branch, in order to correct something and then that unrelated comment by mathstuff from another PR showed up in this one. The avoid confusion I quickly closed it.

**Pull request closed without merging**
