### PR TITLE
clarified README regarding "css add" (refs #256)

### PR DESCRIPTION
**Pull request by GSI**

### CODE REVIEW

**Comment by mathstuf** [comment]
Is it the first or last one which wins?

**Comment by GSI** [comment]
Updated according to your question

**Comment by mathstuf** [comment]
Thanks. FWIW, the name weirdness is to match the API with webkit2 as close as possible.

**Comment by GSI** [comment]
> the name weirdness is to match the API with webkit2 as close as possible.

Supposed so :)

**Pull request merged**
