### PR TITLE
Event dispatch without roundtrip

### PR DESCRIPTION
**Pull request by keis**
Maybe fixing #298 

@GSI could you give this a spin and see if it helps?

### CODE REVIEW

**Comment by GSI** [comment]
Just switched to your branch, but now things like pressing <kbd>i</kbd> (`@cbind  i        = @set_mode insert`) or <kbd>Esc</kbd> (`#@on_event  ESCAPE    event KEYCMD_CLEAR`) are without effect, utlimately denying me to switch modes.

Any idea?

**Comment by keis** [comment]
ACK I see that too. sry. should have tested this better. it's from a bad call to set with the arguments quoted which is not supported by the `set` command. Various dirty fixes comes to mind but I will need to stew on this a bit

**Comment by keis** [comment]
Updated to not quote strings when they are `[a-zA-Z]` which should resolve this without to much specific hacks.

**Comment by GSI** [comment]
Ok. Switched to that build now. Will keep an eye on it.

**Comment by GSI** [comment]
So far I notice that many binds don't work anymore with this:

* key hints don't come up
* search is without effect
* zoom in/out works, but `set zoom_level` fails

```
Commit: v0.9.1-12-gec0f355a
GTK compile: 3.22.6
GTK run: 3.22.6
WebKit compile: 2.4.11
WebKit run: 2.4.11
WebKit2: 0
libsoup compile: 2.56.0
libsoup run: 2.56.0
```

**Comment by keis** [comment]
right. it's likely going to be a fair bit of fallout to cleanup. but is the change resolving the issue where escape would be delayed? I never was able to reproduce that myself.

**Comment by GSI** [comment]
Kind of hard to test without being able to bringing up key hints in the first place :)

But I do have te impression there is less of a lag now.

(I also notice now that hitting <kbd>Esc</kbd> sometimes fails to reset uzbl to **Cmd** mode.)

**Comment by GSI** [comment]
Looks good as far as #298 is concerned.

Will be switching back to master since I miss the hints, but let me know if there's anything else to test.

**Comment by keis** [comment]
Reworked the parsing a bit in the EM and that should resolve some of these issue. I'll keep testing this a bit

**Comment by keis** [comment]
Some stuff I noticed this likely still breaks (or they were already broken ;p)

- [ ] / - search
- [ ] s - set variable binding
- [ ] <Ctrl>a - select all

**Comment by keis** [comment]
ping @mathstuf could you take a look at this

**Comment by keis** [comment]
This has been pretty stable for me for a while now so I'm going to merge it and hope the fallout is not to big :)

**Comment by GSI** [comment]
Updated.

From what I had mentioned only this is still failing:

> zoom in/out works, but set zoom_level fails

**Comment by GSI** [comment]
Good news: I can now consistently reproduce the issue.
Bad news: I can still consistently reproduce the issue.

If I hit <kbd>Esc</kbd> immediately followed by another key, it won't be considered a command:

[uzbl_escape_e.txt](https://github.com/uzbl/uzbl/files/767448/uzbl_escape_e.txt)

*The time window does seem to be considerably shorter than before your fixes though.*

**Comment by keis** [comment]
ok, amazing! 😿 

could you try changing @set_mode for 'set mode'
```
@on_event  ESCAPE    @set_mode
@on_event  ESCAPE    set mode
```

If that does nothing lets take a look at the debug logs from the event manager (start with -navvv)

**Comment by GSI** [comment]
`set mode` changes nothing, but I am closing in on the issue.

As soon as #200 and #338 are merged, I'll push a PR with config settings that appear to affect (or cause?) the present issue.

**Pull request merged**
