### PR TITLE
comm: fix appending doubles to events

### PR DESCRIPTION
**Pull request by mathstuf**
Only the length of the added string needs to be added to the length of
the string.

Introduced in 1a9909161ebb683eb73416df48b2a18ed1cc341c.

---
@keis

### CODE REVIEW

**Comment by keis** [comment]
Actually I think it's supposed to be assigning the len and not adding to it. Reading up on the functions again it looks like g_string_set_size modifies len which I think I was trying to adjust for but I clearly messed that up :sweat:

**Comment by mathstuf** [comment]
The old code (before it became a function) just added the strlen, but either fix should work.

**Comment by keis** [comment]
I think that was buggy but it would only trigger when resizing the string. heh, really wish I would have put some comment in about that because I really can't remember now.

**Comment by mathstuf** [comment]
Looking at `g_string_set_size`, it doesn't look to be the function we really want to be using here. Maybe just using `g_string_append` with a stack array is best here rather than trying to be too clever.

**Comment by keis** [comment]
agreed. it's a bit of a hack to begin with. +1 on using a buffer on the stack.

**Comment by mathstuf** [comment]
Updated to use the buffer on the stack.

**Comment by keis** [comment]
LGTM!

**Pull request merged**
