### PR TITLE
Send LINK_UNHOVER events (fixes #287).

### LINKED ISSUE #287: Late LINK_UNHOVER events (next branch only)
Hi,

In the current next branch with WebKit2, uzbl-core seems to get/relay LINK_UNHOVER events only right before the next LINK_HOVER event. More precisely: when I run
  `uzbl-core -p -c conf google.com`
with a configuration `conf` that contains only the line
  `set status_format \@SELECTED_URI`
then hovering over a link causes a LINK_HOVER event on stdout, and that link appears in the status bar. However, when moving the pointer to a free space on screen, there is no LINK_UNHOVER event, and the link does not disappear from the status bar. (With WebKit1, there is an immediate LINK_UNHOVER event, and the link disappears.) Later on, when hovering onto the next link, there is a LINK_UNHOVER `old-uri`, and then a LINK_HOVER `new-uri` event.

This behavior is a bit annoying, since it means that `@SELECTED_URI` is essentially always set (and sometimes to an outdated value). I guess this is not intended (also since this does not occur with WebKit1).

Output of `uzbl-core --bug-info`:
```
Commit: v0.9.0-72-gb6b9235
GTK compile: 3.20.4
GTK run: 3.20.4
WebKit compile: 2.12.3
WebKit run: 2.12.3
WebKit2: 1
libsoup compile: 2.54.1
libsoup run: 2.54.1
```

### PR DESCRIPTION
**Pull request by hofheinz**
Solution suggested by @keis.

### CODE REVIEW

**Comment by keis** [comment]
Thanks @hofheinz. I won't be able to dig in and test this properly in a bit. But the fix looks simple enough and if that does it I think we can go ahead and merge it.

**Comment by hofheinz** [comment]
I'll test `next` in the next few days and will report any (not-yet-known) problems. (The new libwebkit2 version 2.12.3 fixes some annoying webkit-related crashes, so it's very interesting.) BTW, is general feedback (such as suggestions) welcome? If yes, where should that go? (Github issues?)

**Comment by keis** [comment]
ok. cool :)

and, sure, any suggestion are welcom and tracking them as github issues sounds like a good idea

**Comment by hofheinz** [comment]
Seems to create no problems, at least on the uzbl side. (There are still a number of annyoing webkit crashes on javascript-heavy pages, but the backtraces always point to some webkit part. This is for webkitgtk 2.12.2, 2.12.3, and with and without JIT compilation.)

**Comment by keis** [comment]
Thanks again @hofheinz 
LGTM :joy_cat:

**Pull request merged**
