### PR TITLE
Use C locale when dealing with numbers in api

### PR DESCRIPTION
**Pull request by keis**
Should address the issues in #190

### CODE REVIEW

**Comment by keis** [comment]
@GSI, @f8l Could you give this branch a test and see if it resolves the issue you were seeing in #190 ?

**Comment by GSI** [comment]
Confirmed

*(Variant with `,` separator now fails - as expected)*

**Comment by f8l** [comment]
Seems to work. Thanks for fixing.

**Comment by keis** [comment]
Merged as 0ef215e30e594f0e7a914dfd7792f3dcb87c8269 to master

**Pull request closed without merging**
