### PR TITLE
Fix {navigation,permission}_handler output handling

### PR DESCRIPTION
**Pull request by dan-santana**
Fixes https://github.com/uzbl/uzbl/issues/341.

### CODE REVIEW

**Comment by keis** [comment]
Thanks for the pull-request :)

This change also allows for a lot of extra output, not just newlines, is this is desired for some reason? otherwise using g_strstrip would be better

**Comment by mathstuf** [comment]
Agreed; `g_strstrip` would be better.

Thanks for the fix; I did only ever tested it without the newlines, so this isn't surprising. May have conflicts with `next` (IIRC, it removes the deprecated `USED` keyword).

**Comment by dan-santana** [comment]
The README says:

> [...] If the command returns a string with the **first line** containing only the word `USED`, the navigation is ignored.

which made it implicit that multiline outputs would be gracefully handled.  The description of shell expansions (`@(+command arg1 arg2)@`) also states that it's replaced by the first line of stdout (didn't test it though), so it seems somewhat consistent to allow multiline outputs. Anyway, if the desired behavior is to parse everything as one line, I can fix the docs and check the shell expansion too. What do you think?

About the **next** branch, should I be doing another PR for that? Or this PR should be targeted to there?

**Comment by mathstuf** [comment]
Hmm, indeed. Let's just use the first line then and ignore the rest.

As for next, one of us can merge master into next after this lands.

**Comment by keis** [comment]
ah ok. in that case LGTM!

**Comment by keis** [comment]
as a side note we might want to split out a "first_line" function that we can use in all the places that expect this behaviour. at some point

**Pull request merged**
