### PR TITLE
Adjust webkit version used on travis

### PR DESCRIPTION
**Pull request by keis**

### CODE REVIEW

**Comment by keis** [comment]
Grr

**Comment by mathstuf** [comment]
Yay Ubuntu.

**Comment by mathstuf** [comment]
It should be `libwebkit2gtk-4.0-dev`.

**Comment by keis** [comment]
Not available in trusty and mixing with sid causes all kinds of trouble even installing things. New plan is to run everything with docker so that a up to date fedora base or something can be used.

**Comment by mathstuf** [comment]
Does Travis really not have something more up-to-date?

**Comment by keis** [comment]
From what I kind find the state of os packages is really sad, even trusty (14 LTS release) was a beta feature :/

**Comment by keis** [comment]
Ok. So this at least works now

**Pull request merged**
