### PR TITLE
Don't try to get XID of non-X11 windows

### PR DESCRIPTION
**Pull request by keis**

### CODE REVIEW

**Comment by keis** [comment]
I'll go ahead and merge this pretty simple fix

**Comment by mathstuf** [comment]
Should/can we do something similar for wayland?

**Comment by keis** [comment]
There's something called a "exported window handle" which through what little information there is around seems to be about remote controlling a window. However becoming a exported window is an opt-in operation and I have no idea if it makes sense for uzbl to set that.

**Comment by mathstuf** [comment]
OK. I think it is mostly used so that `dmenu` can place itself relative to the window as if it were a dropdown (which is how I use it). Uzbl may need to export this stuff on its own (though it also may not make sense in Wayland as well).

**Pull request merged**
