### PR TITLE
Sync completions with `set` command, which lost its `=` sign. 

### PR DESCRIPTION
**Pull request by moorchegue**

### CODE REVIEW

**Comment by keis** [comment]
Looks good to me

**Comment by mathstuf** [comment]
Same here; I'll try and test it out this weekend. Thanks!

**Comment by mathstuf** [comment]
Or if @keis can confirm, I'll merge it sooner.

**Comment by keis** [comment]
Tried it for a bit in the sandbox (which needed a whack to find the six module) and it worked fine

**Comment by moorchegue** [comment]
Ah, aboot the six. If you're on Arch, I adopted one older package https://aur.archlinux.org/packages/uzbl-next-git/ and synced it with current state of code in next branch. Less pain setting it up.

**Comment by keis** [comment]
didn't there used to be some test suites for the event manager?

**Pull request merged**
