### PR TITLE
Add webkit2 persistent cookie storage

### LINKED ISSUE #230: Sharing cookies between instances
The cookie commands are only stubs for webkit2 and does not do anything.

Can we make them work again?
Some other way of making this work?

Ref #225

### PR DESCRIPTION
**Pull request by ddevault**
Fixes #230

### CODE REVIEW

**Comment by keis** [comment]
Hi @SirCmpwn and thanks for the PR.

However due to uzbls one window one process model this is not the full story. Loading the initial cookies should work fine and I guess that's something. But two problems remain

* With multiple processes writing to the same file we will have a situation where the on disk cookies is from whatever instance wrote last.
* Cookies accepted in runtime will not be propagated to the other instances

The "traditional" solution to this was to have an external coordinator of this (the event manager) which wolud listen to events and issue add and remove commands to uzbl. In wk1 we could without much trouble inject or remove cookies from the soup session but this is now hidden from us with the cookie manager.

**Comment by SirCmpwn** [comment]
I see what you mean. I have two ideas for solutions:

1. Use shared memory to have a single WebKitCookieManager for all processes
2. Subscribe to WebKitCookieManager's changed signal and announce those changes to the event manager, and sync up the other instances

I think the first strategy would be the most reliable. My concern about the second strategy is that the cookie manager's API doesn't provide a lot of flexibility for manipulating the cookie store.

**Comment by SirCmpwn** [comment]
I'm digging into the webkit source code - improving the cookie manager shouldn't be awful. That's another strategy, I'm getting a dev environment set up for that purpose now.

**Comment by keis** [comment]
The only way I see to achieve 1 would be to move to a single uzbl-core having multiple windows. Hacking around with a custom shared mem thing for webkit stuff is not going to be pretty. I'm not a super big fan of this because processes is very tidy model but there will be many problems like these for caching, local storage etc so we might have to do that anyway.

2nd is the most like what we have for wk1 but that doesn't necessarily mean it's a very good way. This would require either that webkit supported some more operations on the cookie manager or that we could get access to the libsoup cookie jar in the web process which is still around behind the scenes. Neither should be terribly complicated.

The 3rd option would be to improve the builtin cookie manager to deal gracefully with multiple processes. But this would require webkit to have some sort of cookie server so I'm not sure how keen they are on that.

**Pull request closed without merging**
