### PR TITLE
run event manager tests on travis

### PR DESCRIPTION
**Pull request by keis**
I performed some necromancy on the old event-manager tests and patched them back up to snuff. If you enable travis (and coveralls) on uzbl/uzbl we could also have automatic testing of any pull-request coming in through github.

### CODE REVIEW

**Comment by mathstuf** [comment]
Looks good :) . I'm hesitant about Travis because it wants its access to *all* repositories I have access to and I don't feel great about trusting them that much. I wish there were a way to only give them permissions to specific repos :/ . Do you know of a way to do so (without making a special account for it)?

**Comment by keis** [comment]
I wouldn't worry to much the only write permission they have is to modify the webhooks settings. Organisations are a bit special anyway and I think you have to setup the webhook by oldskool copy and paste anyway. I guess you could always add a dummy account with a travis connection to the org and use that api token when configuring the project.

**Comment by keis** [comment]
Or I could always set it up through my account seeing as I already sold my soul to travis :smile_cat:

**Comment by mathstuf** [comment]
I'd be fine with that. What permissions do you need here?

**Comment by keis** [comment]
I think being set as a collaborator on the project should be enough

**Comment by keis** [comment]
hmm. looks like I was mistaken because that did not give me the correct permissions. In my other org it looks like we are all in a group that is set to be admin of the projects we work on so "uzbl/uzbl" but not admin on "uzbl" itself

**Pull request merged**
