### PR TITLE
remove all webkit2 support

### PR DESCRIPTION
**Pull request by keis**
Started working on ripping out the wk2 stuff. not tested yet.

I think after this one `next` should be merged to `master` and then this PR can be reverted on `next` to keep the history in line.

### CODE REVIEW

**Comment by mathstuf** [comment]
>  +18 −2,978

That commit stat :D .

`README.md` needs updated as well. Thanks.

**Comment by mathstuf** [comment]
Done. `next` has this reverted while `master` is now WebKit1-only. Thanks!

**Comment by keis** [comment]
all right awesome :metal:

**Comment by GSI** [comment]
Does this mean we may expect an update to the official Arch repo anytime soon?

**Comment by mathstuf** [comment]
I'm not in charge of Arch's repo, but a release hasn't been tagged yet. A few more things to do yet.

**Comment by logenkain** [comment]
On Thu, Oct 01, 2015 at 06:31:35AM -0700, Ben Boeckel wrote:
> I'm not in charge of Arch's repo, but a release hasn't been tagged yet. A few more things to do yet.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/uzbl/uzbl/pull/163#issuecomment-144726670

Looking forward to a release soon, I'll try to get it  packaged for void-linux
once that happens.

**Pull request merged**
